// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlitedb

import (
	"context"
)

const findActivityById = `-- name: FindActivityById :one
SELECT id, project_id, disp_name, duration FROM activities WHERE id = ?
`

func (q *Queries) FindActivityById(ctx context.Context, id string) (Activity, error) {
	row := q.db.QueryRowContext(ctx, findActivityById, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}

const findAllActivitiesByProject = `-- name: FindAllActivitiesByProject :many
SELECT id, project_id, disp_name, duration FROM activities WHERE project_id = ?
`

func (q *Queries) FindAllActivitiesByProject(ctx context.Context, projectID string) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllActivitiesByProjectAndClosestName = `-- name: FindAllActivitiesByProjectAndClosestName :many
SELECT id, project_id, disp_name, duration FROM activities WHERE project_id = ? AND disp_name LIKE ?
`

type FindAllActivitiesByProjectAndClosestNameParams struct {
	ProjectID string
	DispName  string
}

func (q *Queries) FindAllActivitiesByProjectAndClosestName(ctx context.Context, arg FindAllActivitiesByProjectAndClosestNameParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProjectAndClosestName, arg.ProjectID, arg.DispName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllActivitiesByProjectAndName = `-- name: FindAllActivitiesByProjectAndName :many
SELECT id, project_id, disp_name, duration FROM activities WHERE project_id = ? AND disp_name = ?
`

type FindAllActivitiesByProjectAndNameParams struct {
	ProjectID string
	DispName  string
}

func (q *Queries) FindAllActivitiesByProjectAndName(ctx context.Context, arg FindAllActivitiesByProjectAndNameParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProjectAndName, arg.ProjectID, arg.DispName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllActivitiesByProjectSorted = `-- name: FindAllActivitiesByProjectSorted :many
SELECT a.id, a.project_id, a.disp_name, a.duration , ao.sort_rank
FROM activities a
JOIN activities_ordering ao
    ON a.id = ao.successor_activity_id
    AND a.project_id = ao.project_id
WHERE a.project_id = ?
ORDER BY ao.sort_rank
`

type FindAllActivitiesByProjectSortedRow struct {
	ID        string
	ProjectID string
	DispName  string
	Duration  int64
	SortRank  int64
}

func (q *Queries) FindAllActivitiesByProjectSorted(ctx context.Context, projectID string) ([]FindAllActivitiesByProjectSortedRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProjectSorted, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllActivitiesByProjectSortedRow
	for rows.Next() {
		var i FindAllActivitiesByProjectSortedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
			&i.SortRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO activities (id, project_id, disp_name, duration)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, disp_name, duration
`

type InsertActivityParams struct {
	ID        string
	ProjectID string
	DispName  string
	Duration  int64
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, insertActivity,
		arg.ID,
		arg.ProjectID,
		arg.DispName,
		arg.Duration,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}

const updateActivityDuration = `-- name: UpdateActivityDuration :one
UPDATE activities
SET 
    duration = ?
WHERE id = ?
RETURNING id, project_id, disp_name, duration
`

type UpdateActivityDurationParams struct {
	Duration int64
	ID       string
}

func (q *Queries) UpdateActivityDuration(ctx context.Context, arg UpdateActivityDurationParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, updateActivityDuration, arg.Duration, arg.ID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}

const updateActivityName = `-- name: UpdateActivityName :one
UPDATE activities
SET 
    disp_name = ?
WHERE id = ?
RETURNING id, project_id, disp_name, duration
`

type UpdateActivityNameParams struct {
	DispName string
	ID       string
}

func (q *Queries) UpdateActivityName(ctx context.Context, arg UpdateActivityNameParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, updateActivityName, arg.DispName, arg.ID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}
