// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities_ordering.sql

package sqlitedb

import (
	"context"
)

const insertActivityOrdering = `-- name: InsertActivityOrdering :one
INSERT INTO activities_ordering (id, project_id, successor_activity_id, sort_rank)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, successor_activity_id, sort_rank
`

type InsertActivityOrderingParams struct {
	ID                  string
	ProjectID           string
	SuccessorActivityID string
	SortRank            int64
}

func (q *Queries) InsertActivityOrdering(ctx context.Context, arg InsertActivityOrderingParams) (ActivitiesOrdering, error) {
	row := q.db.QueryRowContext(ctx, insertActivityOrdering,
		arg.ID,
		arg.ProjectID,
		arg.SuccessorActivityID,
		arg.SortRank,
	)
	var i ActivitiesOrdering
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SuccessorActivityID,
		&i.SortRank,
	)
	return i, err
}

const updateActivityOrdering = `-- name: UpdateActivityOrdering :one
UPDATE activities_ordering
SET 
    sort_rank = ?
WHERE successor_activity_id = ?
RETURNING id, project_id, successor_activity_id, sort_rank
`

type UpdateActivityOrderingParams struct {
	SortRank            int64
	SuccessorActivityID string
}

func (q *Queries) UpdateActivityOrdering(ctx context.Context, arg UpdateActivityOrderingParams) (ActivitiesOrdering, error) {
	row := q.db.QueryRowContext(ctx, updateActivityOrdering, arg.SortRank, arg.SuccessorActivityID)
	var i ActivitiesOrdering
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SuccessorActivityID,
		&i.SortRank,
	)
	return i, err
}
