// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlitedb

import (
	"context"
)

const findActivityById = `-- name: FindActivityById :one
SELECT id, project_id, disp_name, duration FROM activities WHERE id = ?
`

func (q *Queries) FindActivityById(ctx context.Context, id string) (Activity, error) {
	row := q.db.QueryRowContext(ctx, findActivityById, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}

const findAllActivitiesByProject = `-- name: FindAllActivitiesByProject :many
SELECT id, project_id, disp_name, duration FROM activities WHERE project_id = ?
`

func (q *Queries) FindAllActivitiesByProject(ctx context.Context, projectID string) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllActivitiesByProjectAndClosestName = `-- name: FindAllActivitiesByProjectAndClosestName :many
SELECT id, project_id, disp_name, duration FROM activities WHERE project_id = ? AND disp_name LIKE ?
`

type FindAllActivitiesByProjectAndClosestNameParams struct {
	ProjectID string
	DispName  string
}

func (q *Queries) FindAllActivitiesByProjectAndClosestName(ctx context.Context, arg FindAllActivitiesByProjectAndClosestNameParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProjectAndClosestName, arg.ProjectID, arg.DispName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllActivitiesByProjectAndName = `-- name: FindAllActivitiesByProjectAndName :many
SELECT id, project_id, disp_name, duration FROM activities WHERE project_id = ? AND disp_name = ?
`

type FindAllActivitiesByProjectAndNameParams struct {
	ProjectID string
	DispName  string
}

func (q *Queries) FindAllActivitiesByProjectAndName(ctx context.Context, arg FindAllActivitiesByProjectAndNameParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProjectAndName, arg.ProjectID, arg.DispName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO activities (id, project_id, disp_name, duration)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, disp_name, duration
`

type InsertActivityParams struct {
	ID        string
	ProjectID string
	DispName  string
	Duration  int64
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, insertActivity,
		arg.ID,
		arg.ProjectID,
		arg.DispName,
		arg.Duration,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}
