// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package db

import (
	"context"
)

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activities WHERE id = ?
`

func (q *Queries) DeleteActivity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteActivity, id)
	return err
}

const findActivityById = `-- name: FindActivityById :one
SELECT id, project_id, disp_name, duration FROM activities WHERE id = ?
`

func (q *Queries) FindActivityById(ctx context.Context, id string) (Activity, error) {
	row := q.db.QueryRowContext(ctx, findActivityById, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}

const findAllActivitiesByNameAndProject = `-- name: FindAllActivitiesByNameAndProject :many
SELECT id, project_id, disp_name, duration FROM activities WHERE disp_name LIKE ? AND project_id = ?
`

type FindAllActivitiesByNameAndProjectParams struct {
	DispName  string
	ProjectID string
}

func (q *Queries) FindAllActivitiesByNameAndProject(ctx context.Context, arg FindAllActivitiesByNameAndProjectParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByNameAndProject, arg.DispName, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllActivitiesByProject = `-- name: FindAllActivitiesByProject :many
SELECT id, project_id, disp_name, duration FROM activities WHERE project_id = ?
`

func (q *Queries) FindAllActivitiesByProject(ctx context.Context, projectID string) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, findAllActivitiesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DispName,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO activities (id, project_id, disp_name, duration)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, disp_name, duration
`

type InsertActivityParams struct {
	ID        string
	ProjectID string
	DispName  string
	Duration  int64
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, insertActivity,
		arg.ID,
		arg.ProjectID,
		arg.DispName,
		arg.Duration,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities
SET 
    disp_name = ?,
    duration = ?
WHERE id = ?
RETURNING id, project_id, disp_name, duration
`

type UpdateActivityParams struct {
	DispName string
	Duration int64
	ID       string
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, updateActivity, arg.DispName, arg.Duration, arg.ID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DispName,
		&i.Duration,
	)
	return i, err
}
