// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dependencies.sql

package db

import (
	"context"
)

const deleteDependency = `-- name: DeleteDependency :exec
DELETE FROM dependencies WHERE id = ?
`

func (q *Queries) DeleteDependency(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDependency, id)
	return err
}

const insertDependency = `-- name: InsertDependency :one
INSERT INTO dependencies (id, project_id, relationship, predecessor_activity_id, successor_activity_id) 
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, relationship, predecessor_activity_id, successor_activity_id
`

type InsertDependencyParams struct {
	ID                    string
	ProjectID             string
	Relationship          string
	PredecessorActivityID string
	SuccessorActivityID   string
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) (Dependency, error) {
	row := q.db.QueryRowContext(ctx, insertDependency,
		arg.ID,
		arg.ProjectID,
		arg.Relationship,
		arg.PredecessorActivityID,
		arg.SuccessorActivityID,
	)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Relationship,
		&i.PredecessorActivityID,
		&i.SuccessorActivityID,
	)
	return i, err
}

const updateDependency = `-- name: UpdateDependency :one
UPDATE dependencies
SET 
    relationship = ?,
    predecessor_activity_id = ?,
    successor_activity_id = ?
WHERE id = ?
RETURNING id, project_id, relationship, predecessor_activity_id, successor_activity_id
`

type UpdateDependencyParams struct {
	Relationship          string
	PredecessorActivityID string
	SuccessorActivityID   string
	ID                    string
}

func (q *Queries) UpdateDependency(ctx context.Context, arg UpdateDependencyParams) (Dependency, error) {
	row := q.db.QueryRowContext(ctx, updateDependency,
		arg.Relationship,
		arg.PredecessorActivityID,
		arg.SuccessorActivityID,
		arg.ID,
	)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Relationship,
		&i.PredecessorActivityID,
		&i.SuccessorActivityID,
	)
	return i, err
}
