// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dependencies.sql

package db

import (
	"context"
)

const deleteDependency = `-- name: DeleteDependency :exec
DELETE FROM dependencies WHERE id = ?
`

func (q *Queries) DeleteDependency(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDependency, id)
	return err
}

const findAllDependenciesByPredecessor = `-- name: FindAllDependenciesByPredecessor :many
SELECT id, project_id, relationship, predecessor_activity_id, successor_activity_id FROM dependencies WHERE predecessor_activity_id = ?
`

func (q *Queries) FindAllDependenciesByPredecessor(ctx context.Context, predecessorActivityID string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, findAllDependenciesByPredecessor, predecessorActivityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dependency
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Relationship,
			&i.PredecessorActivityID,
			&i.SuccessorActivityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllDependenciesByProject = `-- name: FindAllDependenciesByProject :many
SELECT id, project_id, relationship, predecessor_activity_id, successor_activity_id FROM dependencies WHERE project_id = ?
`

func (q *Queries) FindAllDependenciesByProject(ctx context.Context, projectID string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, findAllDependenciesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dependency
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Relationship,
			&i.PredecessorActivityID,
			&i.SuccessorActivityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllDependenciesBySuccessor = `-- name: FindAllDependenciesBySuccessor :many
SELECT id, project_id, relationship, predecessor_activity_id, successor_activity_id FROM dependencies WHERE successor_activity_id = ?
`

func (q *Queries) FindAllDependenciesBySuccessor(ctx context.Context, successorActivityID string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, findAllDependenciesBySuccessor, successorActivityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dependency
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Relationship,
			&i.PredecessorActivityID,
			&i.SuccessorActivityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllDependencyNamesBySuccessor = `-- name: FindAllDependencyNamesBySuccessor :many
SELECT
    d.id,
    d.relationship,
    predecessor.disp_name AS predecessor_activity_name
FROM dependencies d
JOIN activities predecessor
    ON predecessor.id = d.predecessor_activity_id
   AND predecessor.project_id = d.project_id
WHERE d.successor_activity_id = ?
`

type FindAllDependencyNamesBySuccessorRow struct {
	ID                      string
	Relationship            string
	PredecessorActivityName string
}

func (q *Queries) FindAllDependencyNamesBySuccessor(ctx context.Context, successorActivityID string) ([]FindAllDependencyNamesBySuccessorRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllDependencyNamesBySuccessor, successorActivityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllDependencyNamesBySuccessorRow
	for rows.Next() {
		var i FindAllDependencyNamesBySuccessorRow
		if err := rows.Scan(&i.ID, &i.Relationship, &i.PredecessorActivityName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDependencyById = `-- name: FindDependencyById :one
SELECT id, project_id, relationship, predecessor_activity_id, successor_activity_id FROM dependencies WHERE id = ?
`

func (q *Queries) FindDependencyById(ctx context.Context, id string) (Dependency, error) {
	row := q.db.QueryRowContext(ctx, findDependencyById, id)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Relationship,
		&i.PredecessorActivityID,
		&i.SuccessorActivityID,
	)
	return i, err
}

const insertDependency = `-- name: InsertDependency :one
INSERT INTO dependencies (id, project_id, relationship, predecessor_activity_id, successor_activity_id) 
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, relationship, predecessor_activity_id, successor_activity_id
`

type InsertDependencyParams struct {
	ID                    string
	ProjectID             string
	Relationship          string
	PredecessorActivityID string
	SuccessorActivityID   string
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) (Dependency, error) {
	row := q.db.QueryRowContext(ctx, insertDependency,
		arg.ID,
		arg.ProjectID,
		arg.Relationship,
		arg.PredecessorActivityID,
		arg.SuccessorActivityID,
	)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Relationship,
		&i.PredecessorActivityID,
		&i.SuccessorActivityID,
	)
	return i, err
}

const updateDependency = `-- name: UpdateDependency :one
UPDATE dependencies
SET 
    relationship = ?,
    predecessor_activity_id = ?,
    successor_activity_id = ?
WHERE id = ?
RETURNING id, project_id, relationship, predecessor_activity_id, successor_activity_id
`

type UpdateDependencyParams struct {
	Relationship          string
	PredecessorActivityID string
	SuccessorActivityID   string
	ID                    string
}

func (q *Queries) UpdateDependency(ctx context.Context, arg UpdateDependencyParams) (Dependency, error) {
	row := q.db.QueryRowContext(ctx, updateDependency,
		arg.Relationship,
		arg.PredecessorActivityID,
		arg.SuccessorActivityID,
		arg.ID,
	)
	var i Dependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Relationship,
		&i.PredecessorActivityID,
		&i.SuccessorActivityID,
	)
	return i, err
}
